"""The deck engine. Emits HTML, PDF and a Keynote build script from one source.

    python3 deck.py                        placeholder deck, the public base
    python3 deck.py talks/wpsuomi-2026     a real talk, from its talk.py

A talk folder holds talk.py, which overrides EVENT, RUNNING, DECK and friends
below, and receives its own index.html, PDF, OUTLINE.md, bitmaps and
build-key.applescript. talks/ is gitignored, so a talk stays private until it
has been given.

Layouts are cover, statement, pairs, bullets, code and list. Everything else is
derived, so the HTML, the PDF and the Keynote master cannot drift apart.
"""

import html
import pathlib
import re
import subprocess

ROOT = pathlib.Path(__file__).parent

# Code panels are rendered to PNG by headless Chrome and placed in Keynote at
# their natural size. Keynote re-spaces pasted text and distorts scaled images,
# so neither its text layout nor its image scaling is trusted with code.
# Geometry is fixed in pixels here and written into code.css, so the web slide
# and the Keynote bitmap are the same panel.
PANEL_W = 819
CODE_FONT = 26
CODE_LH = 40
CODE_PAD = 26
GROUND = "#F4F0FF"
SCALE = 2  # render at 2x so the bitmap is sharp on a 1920 slide


def panel_height(code):
    return CODE_PAD * 2 + CODE_LH * len(code.split("\n"))


# ------------------------------------------------------------ highlighting

CODE_THEME = {
    "bg": "#1B0B38",
    "text": "#E9DEFF",
    "comment": "#AE9FD6",
    "keyword": "#FF7EDB",
    "string": "#FFB3E1",
    "number": "#F5C2FF",
    "func": "#C79BFF",
    "key": "#8BE9FD",
    "punct": "#B7A6E3",
}

# 45 minute slot minus Q&A. Every slide gets a weight, the weights are scaled to
# fit, and the footer bar shows where you should be by the clock.
SLOT_MIN = 45
QA_MIN = 10
TALK_MIN = None  # SLOT_MIN - QA_MIN, set once a talk is loaded
WEIGHT = {"cover": 0.4, "statement": 0.5, "bullets": 1.0,
          "pairs": 1.0, "list": 1.6, "code": 1.8, "about": 1.5}


def timings():
    """Cumulative minute mark at the end of each slide, scaled to TALK_MIN."""
    w = [WEIGHT[s["layout"]] for s in DECK]
    scale = TALK_MIN / sum(w)
    out, run = [], 0.0
    for x in w:
        run += x * scale
        out.append(run)
    return out


TIMING = None  # filled in main, after DECK is final

KEYWORDS = {
    "php": r"register_post_meta|register_block_bindings_source|register_block_style|acf_register_block_type|get_block_wrapper_attributes|the_field|esc_html|echo|true|false|null|function|return|array",
    "js": r"registerBlockBindingsSource|registerBlockType|const|let|var|function|return|true|false|null|=>",
    "json": r"true|false|null",
    "markup": r"wp:paragraph|wp:[a-z-]+",
}


def detect(code):
    if code.lstrip().startswith("{") or re.search(r'^\s*"\w+":', code, re.M):
        return "json"
    if "<!--" in code or re.search(r"<[a-z]+[ >]", code):
        return "markup"
    if "$" in code or "=>" in code or "<?php" in code or "_(" in code:
        return "php"
    return "js"


def highlight(code, lang=None):
    """Tokenise into spans. Small on purpose: four languages, short snippets."""
    lang = lang or detect(code)
    pattern = "|".join([
        r"(?P<comment>//[^\n]*|#[^\n]*|<!--|-->)",
        r"(?P<key>\"[^\"\n]*\"(?=\s*:))",
        r"(?P<string>'[^'\n]*'|\"[^\"\n]*\")",
        r"(?P<keyword>\b(?:" + KEYWORDS[lang] + r")\b|=>)",
        r"(?P<number>\b\d+(?:\.\d+)?\b)",
        r"(?P<func>\b[a-zA-Z_][\w]*(?=\s*\())",
        r"(?P<punct>[{}\[\]();:,<>=|&.-])",
    ])
    out, pos = [], 0
    for m in re.finditer(pattern, code):
        if m.start() > pos:
            out.append(esc(code[pos:m.start()]))
        kind = m.lastgroup
        out.append(f'<span class="t-{kind}">{esc(m.group())}</span>')
        pos = m.end()
    out.append(esc(code[pos:]))
    return "".join(out)


def emit_code_css():
    t = CODE_THEME
    spans = "\n".join(f'.t-{k} {{ color: {v}; }}'
                      for k, v in t.items() if k not in ("bg", "text"))
    return f'''/* Generated by deck.py. Geometry here is what the Keynote bitmaps are
   rendered at, so do not change it by hand. */

pre {{
  box-sizing: border-box;
  margin: 0;
  padding: {CODE_PAD}px {CODE_PAD + 8}px;
  background: {t["bg"]};
  font-family: var(--mono);
  font-size: {CODE_FONT}px;
  line-height: {CODE_LH}px;
  color: {t["text"]};
  white-space: pre;
  overflow: hidden;
}}

.t-comment {{ font-style: italic; }}
{spans}
'''

# ------------------------------------------------------ placeholder talk
# Overridden wholesale by a talk folder's talk.py.

EVENT = "Event name 2026, City, 1st of January, 2026"
RUNNING = "Talking about something great"
LOGO = ("wpsuomi-logo.svg", "wpsuomi.png", 57, "WP Suomi")  # svg, keynote png, height, alt
VENUE = "Room, venue, city"
KEY_NAME = "Rolle speaker base"
NOTES = ""

# head is the Unbounded part, em the Instrument Serif italic part.
DECK = [
    dict(layout="cover", head="Talking about", em="something great",
         standfirst=["One line that says what this is,", "and one that says why it matters"]),

    dict(layout="about", sections=[
        ("About", "me", "Two short sections for the speaker slide. Photos stack full-bleed on the right when the talk supplies them."),
        ("And", "the company", "Keep each one to three lines. The heading does the work, the paragraph gives the room something to read while you talk."),
    ]),

    dict(layout="statement", head="One idea,", em="said plainly",
         standfirst=["For section breaks, and for the lines", "you want the room to remember."]),

    dict(layout="pairs", head="Four things,", em="side by side", pairs=[
        ("Label", "Two lines of body copy at most, or it stops being a label."),
        ("Contrast", "Everything on the slide clears 7.5:1 against the ground."),
        ("Type", "Unbounded for the noun, Instrument Serif for the counter-phrase."),
        ("Space", "Hierarchy is size and space. No borders, no cards."),
    ]),

    dict(layout="bullets", head="A short", em="list", items=[
        "No borders.",
        "No ALL CAPS, eyebrows and labels included.",
        "No rounded cards with tinted fills.",
        "Type runs large, and headings stay short.",
    ]),

    dict(layout="list", head="What the base", em="gives you", items=[
        "Cover with portrait",
        "Statement",
        "Pairs",
        "Bullets",
        "A dense list like this one",
        "Code panels",
        "Real syntax highlighting",
        "A timing bar, not page numbers",
        "HTML output",
        "PDF output",
        "A Keynote master",
        "One source for all three",
    ]),

    dict(layout="code", head="One field,", em="two ways",
         left_label="With the plugin", left_code="the_field( 'subtitle' );",
         right_label="With core", right_code="register_post_meta( 'post', 'subtitle', [\n  'type'         => 'string',\n  'single'       => true,\n  'show_in_rest' => true,\n] );",
         takeaway="Four more lines, and the value now has a type, a schema and a REST route. The theme stops being the only thing that knows the field exists."),

    dict(layout="statement", head="Kiitos.", em="Questions?",
         standfirst=["Rolle Laukkarinen", "rolle.social"]),
]

# ---------------------------------------------------------------- HTML

SOCIAL_ICONS = """<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" viewBox="0 0 16 16" aria-hidden="true"><path d="M11.19 12.195c2.016-.24 3.77-1.475 3.99-2.603.348-1.778.32-4.339.32-4.339 0-3.47-2.286-4.488-2.286-4.488C12.062.238 10.083.017 8.027 0h-.05C5.92.017 3.942.238 2.79.765c0 0-2.285 1.017-2.285 4.488l-.002.662c-.004.64-.007 1.35.011 2.091.083 3.394.626 6.74 3.78 7.57 1.454.383 2.703.463 3.709.408 1.823-.1 2.847-.647 2.847-.647l-.06-1.317s-1.303.41-2.767.36c-1.45-.05-2.98-.156-3.215-1.928a3.614 3.614 0 0 1-.033-.496s1.424.346 3.228.428c1.103.05 2.137-.064 3.188-.189zm1.613-2.47H11.13v-4.08c0-.859-.364-1.295-1.091-1.295-.804 0-1.207.517-1.207 1.541v2.233H7.168V5.89c0-1.024-.403-1.541-1.207-1.541-.727 0-1.091.436-1.091 1.296v4.079H3.197V5.522c0-.859.22-1.541.66-2.046.456-.505 1.052-.764 1.793-.764.856 0 1.504.328 1.933.983L8 4.39l.417-.695c.429-.655 1.077-.983 1.934-.983.74 0 1.336.259 1.791.764.442.505.661 1.187.661 2.046v4.203z"></path></svg>
          <svg width="32" height="32" viewBox="0 0 192 192" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><path fill="currentColor" d="M141.537 88.9883C140.71 88.5919 139.87 88.2104 139.019 87.8451C137.537 60.5382 122.616 44.905 97.5619 44.745C97.4484 44.7443 97.3355 44.7443 97.222 44.7443C82.2364 44.7443 69.7731 51.1409 62.102 62.7807L75.881 72.2328C81.6116 63.5383 90.6052 61.6848 97.2286 61.6848C97.3051 61.6848 97.3819 61.6848 97.4576 61.6855C105.707 61.7381 111.932 64.1366 115.961 68.814C118.893 72.2193 120.854 76.925 121.825 82.8638C114.511 81.6207 106.601 81.2385 98.145 81.7233C74.3247 83.0954 59.0111 96.9879 60.0396 116.292C60.5615 126.084 65.4397 134.508 73.775 140.011C80.8224 144.663 89.899 146.938 99.3323 146.423C111.79 145.74 121.563 140.987 128.381 132.296C133.559 125.696 136.834 117.143 138.28 106.366C144.217 109.949 148.617 114.664 151.047 120.332C155.179 129.967 155.42 145.8 142.501 158.708C131.182 170.016 117.576 174.908 97.0135 175.059C74.2042 174.89 56.9538 167.575 45.7381 153.317C35.2355 139.966 29.8077 120.682 29.6052 96C29.8077 71.3178 35.2355 52.0336 45.7381 38.6827C56.9538 24.4249 74.2039 17.11 97.0132 16.9405C119.988 17.1113 137.539 24.4614 149.184 38.788C154.894 45.8136 159.199 54.6488 162.037 64.9503L178.184 60.6422C174.744 47.9622 169.331 37.0357 161.965 27.974C147.036 9.60668 125.202 0.195148 97.0695 0H96.9569C68.8816 0.19447 47.2921 9.6418 32.7883 28.0793C19.8819 44.4864 13.2244 67.3157 13.0007 95.9325L13 96L13.0007 96.0675C13.2244 124.684 19.8819 147.514 32.7883 163.921C47.2921 182.358 68.8816 191.806 96.9569 192H97.0695C122.03 191.827 139.624 185.292 154.118 170.811C173.081 151.866 172.51 128.119 166.26 113.541C161.776 103.087 153.227 94.5962 141.537 88.9883ZM98.4405 129.507C88.0005 130.095 77.1544 125.409 76.6196 115.372C76.2232 107.93 81.9158 99.626 99.0812 98.6368C101.047 98.5234 102.976 98.468 104.871 98.468C111.106 98.468 116.939 99.0737 122.242 100.233C120.264 124.935 108.662 128.946 98.4405 129.507Z"></path></svg>
          <svg width="35" height="32" viewBox="0 0 360 320" xmlns="http://www.w3.org/2000/svg" fill="currentColor" aria-hidden="true"><path d="M180 141.964C163.699 110.262 119.308 51.1817 78.0347 22.044C38.4971 -5.86834 23.414 -1.03207 13.526 3.43594C2.08093 8.60755 0 26.1785 0 36.5164C0 46.8542 5.66748 121.272 9.36416 133.694C21.5786 174.738 65.0603 188.607 105.104 184.156C107.151 183.852 109.227 183.572 111.329 183.312C109.267 183.642 107.19 183.924 105.104 184.156C46.4204 192.847 -5.69621 214.233 62.6582 290.33C137.848 368.18 165.705 273.637 180 225.702C194.295 273.637 210.76 364.771 295.995 290.33C360 225.702 313.58 192.85 254.896 184.158C252.81 183.926 250.733 183.645 248.671 183.315C250.773 183.574 252.849 183.855 254.896 184.158C294.94 188.61 338.421 174.74 350.636 133.697C354.333 121.275 360 46.8568 360 36.519C360 26.1811 357.919 8.61012 346.474 3.43851C336.586 -1.02949 321.503 -5.86576 281.965 22.0466C240.692 51.1843 196.301 110.262 180 141.964Z"></path></svg>
          <svg viewBox="0 0 24 24" width="32" height="32" xmlns="http://www.w3.org/2000/svg" fill="currentColor" aria-hidden="true"><path d="M12 0C8.74 0 8.333.015 7.053.072 5.775.132 4.905.333 4.14.63c-.789.306-1.459.717-2.126 1.384S.935 3.35.63 4.14C.333 4.905.131 5.775.072 7.053.012 8.333 0 8.74 0 12s.015 3.667.072 4.947c.06 1.277.261 2.148.558 2.913a5.885 5.885 0 0 0 1.384 2.126A5.868 5.868 0 0 0 4.14 23.37c.766.296 1.636.499 2.913.558C8.333 23.988 8.74 24 12 24s3.667-.015 4.947-.072c1.277-.06 2.148-.262 2.913-.558a5.898 5.898 0 0 0 2.126-1.384 5.86 5.86 0 0 0 1.384-2.126c.296-.765.499-1.636.558-2.913.06-1.28.072-1.687.072-4.947s-.015-3.667-.072-4.947c-.06-1.277-.262-2.149-.558-2.913a5.89 5.89 0 0 0-1.384-2.126A5.847 5.847 0 0 0 19.86.63c-.765-.297-1.636-.499-2.913-.558C15.667.012 15.26 0 12 0zm0 2.16c3.203 0 3.585.016 4.85.071 1.17.055 1.805.249 2.227.415.562.217.96.477 1.382.896.419.42.679.819.896 1.381.164.422.36 1.057.413 2.227.057 1.266.07 1.646.07 4.85s-.015 3.585-.074 4.85c-.061 1.17-.256 1.805-.421 2.227a3.81 3.81 0 0 1-.899 1.382 3.744 3.744 0 0 1-1.38.896c-.42.164-1.065.36-2.235.413-1.274.057-1.649.07-4.859.07-3.211 0-3.586-.015-4.859-.074-1.171-.061-1.816-.256-2.236-.421a3.716 3.716 0 0 1-1.379-.899 3.644 3.644 0 0 1-.9-1.38c-.165-.42-.359-1.065-.42-2.235-.045-1.26-.061-1.649-.061-4.844 0-3.196.016-3.586.061-4.861.061-1.17.255-1.814.42-2.234.21-.57.479-.96.9-1.381.419-.419.81-.689 1.379-.898.42-.166 1.051-.361 2.221-.421 1.275-.045 1.65-.06 4.859-.06l.045.03zm0 3.678a6.162 6.162 0 1 0 0 12.324 6.162 6.162 0 1 0 0-12.324zM12 16c-2.21 0-4-1.79-4-4s1.79-4 4-4 4 1.79 4 4-1.79 4-4 4zm7.846-10.405a1.441 1.441 0 0 1-2.88 0 1.44 1.44 0 0 1 2.88 0z"></path></svg>
          <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" viewBox="0 0 512 512" aria-hidden="true"><path d="M226.8 31l-133 256.6h78.4l54.7-102 54.2 102h77.8L226.8 31zm132 256.6l-38.6 77.5-39.2-77.5h-59.4L320.2 481l98-193.4h-59.4z"></path></svg>
          <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z"></path></svg>
          <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" aria-hidden="true"><path d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"></path></svg>"""


def esc(s):
    return html.escape(s, quote=False)


DASH = '<span class="dash">\u2014</span>'


def h2(slide):
    return f'<h2>{esc(slide["head"])} <em>{esc(slide["em"])}</em></h2>'


BAR_W = 300
PROG_W = 460
PROG_H = 32


def progress_html(n):
    mins = TIMING[n - 1]
    pct = 100.0 * mins / TALK_MIN
    return (f'<div class="progress">'
            f'<span><b>{round(mins)}</b>/{TALK_MIN} min</span>'
            f'<div class="bar"><i style="width:{pct:.1f}%"></i></div></div>')


def footer(n):
    return (f'<div class="footer"><div>{esc(RUNNING)}</div>'
            f'{progress_html(n)}</div>')


def html_slide(slide, n):
    lay = slide["layout"]

    if lay == "cover":
        sf = "<br>".join(esc(l) for l in slide["standfirst"])
        return f'''<section class="slide title">
  <div class="title__column">
    <div class="event">
      <img class="event__logo" src="{P}assets/{LOGO[0]}" alt="{esc(LOGO[3])}">
      <div class="eyebrow">{esc(EVENT)}</div>
    </div>
    <div class="title__headline">
      <h1>{esc(slide["head"])}<br><em>{esc(slide["em"])}</em></h1>
      <p class="standfirst">{sf}</p>
    </div>
    <div class="title__footer">
      <div class="byline">
        <strong>Rolle Laukkarinen</strong>
        <span>Founder and CTO, Digitoimisto Dude Oy</span>
      </div>
      <div class="social">
        <span class="social__icons">
          {SOCIAL_ICONS}
        </span>
        <span class="social__url">\u2192\u00a0\u00a0rolle.social</span>
      </div>
    </div>
  </div>
  <img class="portrait" src="{P}assets/portrait.jpg" alt="Rolle Laukkarinen">
</section>'''

    if lay == "statement":
        sf = "<br>".join(esc(l) for l in slide["standfirst"])
        return f'''<section class="slide statement">
  <div class="body">
    <h1>{esc(slide["head"])}<br><em>{esc(slide["em"])}</em></h1>
    <p class="standfirst">{sf}</p>
  </div>
  {footer(n)}
</section>'''

    if lay == "pairs":
        cells = "\n".join(
            f'    <div class="pair">\n'
            f'      <div class="pair__label">{esc(a)}</div>\n'
            f'      <div class="pair__body">{esc(b)}</div>\n'
            f'    </div>'
            for a, b in slide["pairs"])
        return f'''<section class="slide content">
  {h2(slide)}
  <div class="body">
  <div class="pairs">
{cells}
  </div>
  </div>
  {footer(n)}
</section>'''

    if lay == "bullets":
        items = "\n".join(f'    <li>{DASH}<span>{esc(i)}</span></li>' for i in slide["items"])
        return f'''<section class="slide content">
  {h2(slide)}
  <div class="body">
  <ul class="bullets">
{items}
  </ul>
  </div>
  {footer(n)}
</section>'''

    if lay == "list":
        items = "\n".join(f'    <li>{DASH}<span>{esc(i)}</span></li>' for i in slide["items"])
        return f'''<section class="slide content">
  {h2(slide)}
  <div class="body">
  <ul class="ways">
{items}
  </ul>
  </div>
  {footer(n)}
</section>'''

    if lay == "code":
        return f'''<section class="slide content code">
  {h2(slide)}
  <div class="body">
  <div class="code__columns">
    <div class="code__column">
      <div class="code__label">{esc(slide["left_label"])}</div>
      <pre>{highlight(slide["left_code"])}</pre>
    </div>
    <div class="code__column">
      <div class="code__label">{esc(slide["right_label"])}</div>
      <pre>{highlight(slide["right_code"])}</pre>
    </div>
  </div>
  <p class="takeaway">{esc(slide["takeaway"])}</p>
  </div>
  {footer(n)}
</section>'''

    if lay == "about":
        sections = "\n".join(
            f'''      <div class="about__section">
        <h2>{esc(head)} <em>{esc(em)}</em></h2>
        <p class="about__text">{esc(text)}</p>
      </div>''' for head, em, text in slide["sections"])
        photos = "".join(f'<img src="{esc(ph)}" alt="">' for ph in slide.get("photos", []))
        side = f'\n  <div class="about__photos">{photos}</div>' if photos else ""
        return f'''<section class="slide about">
  <div class="about__column">
    <div class="body">
{sections}
    </div>
    {footer(n)}
  </div>{side}
</section>'''

    raise ValueError(lay)


def emit_html():
    body = "\n\n".join(html_slide(s, i + 1) for i, s in enumerate(DECK))
    return f'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{esc(RUNNING)}</title>
<link rel="stylesheet" href="{P}base.css">
<link rel="stylesheet" href="{P}code.css">
</head>
<body>

{body}

</body>
</html>
'''


# ---------------------------------------------------------- AppleScript
#
# Keynote gets no layout of its own. Chrome lays the HTML out, MEASURE_JS reads
# back every text line and image box, and the script below places exactly that.
# A design change is therefore a CSS change, and Keynote follows it.

MEASURE_JS = r"""
(async () => {
  await document.fonts.ready;
  const blockOf = el => {
    while (el && getComputedStyle(el).display.startsWith('inline')) el = el.parentElement;
    return el;
  };
  const skip = n => n.parentElement.closest('pre, .progress, svg, .social__icons') || !n.nodeValue.trim();
  const out = [];
  for (const sec of document.querySelectorAll('section.slide')) {
    const R = sec.getBoundingClientRect();
    const box = el => { const r = el.getBoundingClientRect();
      return {x: r.left - R.left, y: r.top - R.top, w: r.width, h: r.height}; };
    const images = [];
    for (const [kind, sel] of [['portrait', '.portrait'], ['logo', '.event__logo'],
        ['photo', '.about__photos img'], ['code', 'pre'], ['progress', '.progress'],
        ['icons', '.social__icons']])
      sec.querySelectorAll(sel).forEach(e => images.push({kind, src: e.getAttribute('src') || '', ...box(e)}));

    // One item per block, so Keynote wraps paragraphs itself and they stay
    // editable as one box. Forced <br> breaks start a new item; soft wraps do not.
    const lines = [], range = document.createRange();
    const walker = document.createTreeWalker(sec, NodeFilter.SHOW_TEXT | NodeFilter.SHOW_ELEMENT, {acceptNode: n => {
      if (n.nodeType === 1)
        return n.nodeName === 'BR' ? NodeFilter.FILTER_ACCEPT
          : n.matches('pre, .progress, svg, .social__icons') ? NodeFilter.FILTER_REJECT : NodeFilter.FILTER_SKIP;
      return n.nodeValue.trim() ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_REJECT;
    }});
    let cur = null, curBlock = null, breakNext = false, prevLeft = 0, prevRight = 0, node;
    while ((node = walker.nextNode())) {
      if (node.nodeType === 1) { breakNext = true; continue; }
      const el = node.parentElement, cs = getComputedStyle(el), block = blockOf(el);
      const st = {family: cs.fontFamily, weight: cs.fontWeight, style: cs.fontStyle,
                  size: parseFloat(cs.fontSize), color: cs.color};
      const key = JSON.stringify(st), t = node.nodeValue;
      for (let i = 0; i < t.length; i++) {
        range.setStart(node, i); range.setEnd(node, i + 1);
        const rs = range.getClientRects();
        const space = /\s/.test(t[i]);
        if (!rs.length) { if (space && cur && !breakNext) cur.pendingSpace = true; continue; }
        const r = rs[0], x = r.left - R.left, y = r.top - R.top;
        const fresh = !cur || block !== curBlock || breakNext ||
          (!cur.wrapped && x - prevRight > 0.6 * st.size && Math.abs(y - cur.top) < st.size);
        if (fresh && space) continue;
        if (fresh) {
          const br = block.getBoundingClientRect();
          cur = {x, top: y, bottom: y + r.height, right: x, width: br.right - R.left - x, wrapped: false, runs: []};
          lines.push(cur); curBlock = block; breakNext = false;
        } else if (!space && x < prevLeft - 1) {
          cur.wrapped = true;
        }
        if (!cur.wrapped) {
          cur.top = Math.min(cur.top, y); cur.bottom = Math.max(cur.bottom, y + r.height);
          if (!space) cur.right = Math.max(cur.right, x + r.width);
        }
        let ch = space ? ' ' : t[i];
        if (cur.pendingSpace && !space) ch = ' ' + ch;
        cur.pendingSpace = false;
        const last = cur.runs[cur.runs.length - 1];
        if (last && last.text.endsWith(' ') && ch === ' ') { prevLeft = x; prevRight = x + r.width; continue; }
        if (last && last.key === key) last.text += ch; else cur.runs.push({key, ...st, text: ch});
        prevLeft = x; prevRight = x + r.width;
      }
    }
    for (const l of lines) {
      const z = l.runs[l.runs.length - 1]; z.text = z.text.replace(/\s+$/, '');
      l.runs = l.runs.filter(r => r.text.length);
      l.runs.forEach(r => delete r.key);
      delete l.pendingSpace;
    }
    out.push({images, lines});
  }
  const tag = document.createElement('script');
  tag.type = 'application/json'; tag.id = '__measure'; tag.textContent = JSON.stringify(out);
  document.body.appendChild(tag);
})();
"""


def measure(page):
    """Lay the deck out in Chrome and read back where everything landed."""
    import json
    src = page.read_text()
    src = src.replace("<head>", f'<head>\n<base href="{page.parent.as_uri()}/">', 1)
    src = src.replace("</body>", f"<script>{MEASURE_JS}</script>\n</body>", 1)
    tmp = GEN / "_sheets" / "measure.html"
    tmp.parent.mkdir(parents=True, exist_ok=True)
    tmp.write_text(src)
    dom = subprocess.run(
        [CHROME, "--headless", "--disable-gpu", "--hide-scrollbars",
         "--virtual-time-budget=20000", "--window-size=1920,1080",
         "--dump-dom", tmp.as_uri()],
        check=True, capture_output=True, text=True).stdout
    m = re.search(r'<script type="application/json" id="__measure">(.*?)</script>', dom, re.S)
    if not m:
        raise SystemExit("measure: Chrome returned no layout, fonts may not have loaded")
    return json.loads(m.group(1))


def a(s):
    """One AppleScript string literal."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def ps_font(run):
    fam, w = run["family"].lower(), int(run["weight"])
    if "unbounded" in fam:
        return "Unbounded-Regular_ExtraBold" if w >= 700 else "Unbounded-Regular_SemiBold"
    if "instrument serif" in fam:
        return "InstrumentSerif-Italic" if run["style"] == "italic" else "InstrumentSerif-Regular"
    if "geist mono" in fam:
        return "GeistMono-Regular"
    return {500: "Geist-Medium", 600: "Geist-SemiBold", 700: "Geist-Bold"}.get(w, "Geist-Regular")


def ks_color(css):
    r, g, b = (int(v) for v in re.findall(r"\d+", css)[:3])
    return f"{{{r * 257}, {g * 257}, {b * 257}}}"


# Keynote draws text inside its text item's inner inset. (x, y) in px to
# subtract from Chrome's glyph box, calibrated 24.9.2026 against a Keynote
# export of all 38 slides: the same at every size, per face.
INSET = {"unbounded": (6, 5), "serif": (5, 5), "geist": (4, 5)}
# ponytail: one-off for the cover's 174px italic, whose overhang Keynote draws
# 8px further left. Replace with a per-size curve if more huge italics appear.
HUGE_ITALIC = (150, -8)


def face(run):
    fam = run["family"].lower()
    return "unbounded" if "unbounded" in fam else "serif" if "instrument" in fam else "geist"


def as_text(line, var):
    runs = line["runs"]
    text = "".join(r["text"] for r in runs)
    big = max(runs, key=lambda r: r["size"])
    ix, iy = INSET[face(big)]
    if runs[0]["style"] == "italic" and runs[0]["size"] > HUGE_ITALIC[0]:
        ix += HUGE_ITALIC[1]
    x, y = line["x"] - ix, line["top"] - iy
    # The block's own width, plus slack: Keynote has no letter-spacing control,
    # so its Unbounded runs a little wider than Chrome's.
    w = max(line["width"], line["right"] - line["x"]) * 1.04 + 16
    h = line["bottom"] - line["top"] + 24
    first = runs[0]
    out = [f'      set {var} to make new text item with properties {{object text:{a(text)}, position:{{{x:.0f}, {y:.0f}}}, width:{w:.0f}, height:{h:.0f}}}\n',
           f'      tell object text of {var}\n'
           f'        set its font to "{ps_font(first)}"\n'
           f'        set its size to {first["size"]:g}\n'
           f'        set its color to {ks_color(first["color"])}\n'
           f'      end tell\n']
    pos = len(first["text"]) + 1
    for r in runs[1:]:
        end = pos + len(r["text"]) - 1
        out.append(f'      tell characters {pos} thru {end} of object text of {var}\n'
                   f'        set its font to "{ps_font(r)}"\n'
                   f'        set its size to {r["size"]:g}\n'
                   f'        set its color to {ks_color(r["color"])}\n'
                   f'      end tell\n')
        pos = end + 1
    # Keynote ignores the requested height: it fits the box to the text and keeps
    # the box centre fixed, on creation and again on every size change. Setting
    # the position last pins the top edge where the measurement says.
    out.append(f'      set position of {var} to {{{x:.0f}, {y:.0f}}}\n')
    return "".join(out)


def as_image(path_expr, x, y, w, h):
    return (f'      make new image with properties {{file:(POSIX file ({path_expr})), '
            f'position:{{{x:.0f}, {y:.0f}}}, width:{w:.0f}, height:{h:.0f}}}\n')


ICONS_ASPECT = 706 / 64  # icons.png from build-assets.sh


def a_multi(s):
    """A string literal whose line breaks become AppleScript returns."""
    return " & return & ".join(a(line) for line in s.split("\n"))


def as_slide(m, n, var):
    out = [f"    tell {var}\n",
           as_image('assetDir & "bg.png"', 0, 0, 1920, 1080)]
    sides = iter(("left", "right"))
    for im in m["images"]:
        k, x, y, w, h = im["kind"], im["x"], im["y"], im["w"], im["h"]
        if k == "portrait":
            out.append(as_image('repoRoot & "/assets/portrait-crop.jpg"', x, y, w, h))
        elif k == "logo":
            out.append(as_image(f'assetDir & "{LOGO[1]}"', x, y, w, h))
        elif k == "photo":
            rel = (OUT / im["src"]).resolve().relative_to(ROOT).as_posix()
            out.append(as_image(f'repoRoot & "/{rel}"', x, y, w, h))
        elif k == "code":
            if abs(w - PANEL_W) > 1.5:
                print(f"warning: slide {n} code panel is {w:.0f}px wide, bitmaps are {PANEL_W}")
            out.append(as_image(f'genDir & "code-{n}-{next(sides)}.png"', x, y, w, h))
        elif k == "progress":
            out.append(as_image(f'genDir & "prog-{n}.png"', x + w - PROG_W, y + h / 2 - PROG_H / 2, PROG_W, PROG_H))
        elif k == "icons":
            out.append(as_image('assetDir & "icons.png"', x, y, h * ICONS_ASPECT, h))
    for i, line in enumerate(m["lines"]):
        out.append(as_text(line, f"t{i}"))
    notes = DECK[n - 1].get("notes")
    if notes:
        out.append(f"      set presenter notes to {a_multi(notes.strip())}\n")
    out.append("    end tell\n")
    return "".join(out)


def emit_applescript(layout):
    makes = "".join(
        f'    set s{i + 1} to make new slide with properties {{base slide:blankMaster}}\n'
        for i in range(1, len(layout)))
    bodies = "\n".join(
        as_slide(m, i + 1, "slide 1" if i == 0 else f"s{i + 1}")
        for i, m in enumerate(layout))
    rel = lambda p: p.relative_to(ROOT).as_posix()
    return f"""-- Generated by deck.py from the measured HTML layout. Do not edit.
-- Run: osascript {rel(SCRIPT)} --force
--
-- This overwrites {KEY.name} wholesale, losing anything done by hand in
-- Keynote, so it will not run without --force.

on run argv
if argv does not contain "--force" then
  error "Refusing to rebuild: {rel(KEY)} may hold Keynote edits that only exist there. Re-run with --force to overwrite it." number 1
end if

set repoRoot to (do shell script "cd " & quoted form of ((POSIX path of (path to home folder)) & "Projects/keynote-base") & " && pwd")
set assetDir to repoRoot & "/build/keyassets/"
set genDir to repoRoot & "/{rel(GEN)}/"
set outPath to repoRoot & "/{rel(KEY)}"

tell application "Keynote"
  activate
  set doc to make new document with properties {{width:1920, height:1080}}
  tell doc
    set blankMaster to master slide "Blank"
    set base slide of slide 1 to blankMaster
{makes}
{bodies}
    save doc in POSIX file outPath
  end tell
end tell
end run
"""


CHROME = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"


def shoot(page, w, h, out_png):
    """One Chrome launch. Launching it per image costs ~40s each, so don't."""
    subprocess.run(
        [CHROME, "--headless", "--disable-gpu", "--hide-scrollbars",
         f"--screenshot={out_png}", f"--window-size={w},{h}", str(page)],
        check=True, capture_output=True)


def crop(sheet, x, y, w, h, out_png):
    subprocess.run(
        ["ffmpeg", "-y", "-loglevel", "error", "-i", str(sheet),
         "-vf", f"crop={w}:{h}:{x}:{y}", "-frames:v", "1", str(out_png)],
        check=True)


def render_code_panels():
    """Every code block on one sheet, then cropped out. Same CSS as the web slide."""
    out = GEN
    tmp = out / "_sheets"
    tmp.mkdir(parents=True, exist_ok=True)

    blocks, y = [], 0
    for n, slide in enumerate(DECK, 1):
        if slide["layout"] != "code":
            continue
        for side in ("left", "right"):
            code = slide[f"{side}_code"]
            h = panel_height(code)
            blocks.append((f"code-{n}-{side}", code, y, h))
            y += h

    body = "".join(
        f'<pre style="height:{h}px">{highlight(c)}</pre>' for _, c, _, h in blocks)
    page = tmp / "code.html"
    page.write_text(f"""<!doctype html><meta charset="utf-8">
<link rel="stylesheet" href="{(ROOT / 'code.css').as_uri()}">
<style>
  html, body {{ margin: 0; padding: 0; background: {CODE_THEME['bg']}; }}
  :root {{ --mono: "Geist Mono", ui-monospace, monospace; }}
  body {{ zoom: {SCALE}; }}
  pre {{ width: {PANEL_W}px; }}
</style>
{body}""")
    sheet = tmp / "code-sheet.png"
    shoot(page, PANEL_W * SCALE, y * SCALE, sheet)
    for name, _, top, h in blocks:
        crop(sheet, 0, top * SCALE, PANEL_W * SCALE, h * SCALE, out / f"{name}.png")
    return len(blocks)


def render_bars():
    """Every footer progress element on one sheet, then cropped out."""
    out = GEN
    tmp = out / "_sheets"
    tmp.mkdir(parents=True, exist_ok=True)

    rows = "".join(
        f'<div class="wrap">{progress_html(n)}</div>'
        for n in range(1, len(DECK) + 1))
    page = tmp / "prog.html"
    page.write_text(f"""<!doctype html><meta charset="utf-8">
<link rel="stylesheet" href="{(ROOT / 'base.css').as_uri()}">
<style>
  html, body {{ margin: 0; padding: 0; background: {GROUND}; }}
  body {{ zoom: {SCALE}; font-family: "Geist", sans-serif; }}
  .wrap {{ display: flex; justify-content: flex-end; align-items: center;
           width: {PROG_W}px; height: {PROG_H}px; }}
</style>
{rows}""")
    sheet = tmp / "prog-sheet.png"
    shoot(page, PROG_W * SCALE, PROG_H * SCALE * len(DECK), sheet)
    for n in range(1, len(DECK) + 1):
        crop(sheet, 0, (n - 1) * PROG_H * SCALE,
             PROG_W * SCALE, PROG_H * SCALE, out / f"prog-{n}.png")


def title(slide):
    if "sections" in slide:
        return " / ".join(f"{h} {e}" for h, e, _ in slide["sections"])
    return f"{slide['head']} {slide['em']}"


def emit_outline():
    rows = []
    for i, (s, m) in enumerate(zip(DECK, TIMING), 1):
        rows.append(f"| {i} | {title(s)} | {s['layout']} | {m:.1f} |")
    body = "\n".join(rows)
    spoken = "\n\n".join(
        f"### {i}. {title(s)}\n\n{s['notes'].strip()}"
        for i, s in enumerate(DECK, 1) if s.get("notes"))
    if spoken:
        body += "\n\n## Speaker notes\n\n" + spoken
    return f"""# {DECK[0]['head']} {DECK[0]['em']}

Generated by deck.py. Do not edit the running order here; edit DECK in talk.py.

{EVENT}. {VENUE}.
{SLOT_MIN} min slot, {QA_MIN} min Q&A, so {TALK_MIN} min of talking.
{len(DECK)} slides.

## Running order

| # | Slide | Layout | Minute |
| -- | -- | -- | -- |
{body}
{NOTES}"""


def print_pdf(page, pdf):
    subprocess.run(
        [CHROME, "--headless", "--no-pdf-header-footer",
         f"--print-to-pdf={pdf}", str(page)],
        check=True, capture_output=True)


if __name__ == "__main__":
    import runpy
    import sys

    if len(sys.argv) > 1:
        TALK = (ROOT / sys.argv[1]).resolve()
        loaded = runpy.run_path(str(TALK / "talk.py"))
        globals().update({k: v for k, v in loaded.items() if k.isupper()})
        OUT, GEN = TALK, TALK / "keyassets"
        SCRIPT, KEY = TALK / "build-key.applescript", TALK / f"{KEY_NAME}.key"
        PDF = TALK / f"{KEY_NAME}.pdf"
        P = "../../"
    else:
        OUT, GEN = ROOT, ROOT / "build" / "keyassets"
        SCRIPT, KEY = ROOT / "scripts" / "build-key.applescript", ROOT / "build" / f"{KEY_NAME}.key"
        PDF = ROOT / "build" / "keynote-base.pdf"
        P = ""

    TALK_MIN = SLOT_MIN - QA_MIN
    TIMING = timings()
    (ROOT / "code.css").write_text(emit_code_css())
    (OUT / "index.html").write_text(emit_html())
    GEN.mkdir(parents=True, exist_ok=True)
    SCRIPT.write_text(emit_applescript(measure(OUT / "index.html")))
    if OUT != ROOT:
        (OUT / "OUTLINE.md").write_text(emit_outline())
    made = render_code_panels()
    render_bars()
    print_pdf(OUT / "index.html", PDF)
    print(f"{len(DECK)} slides, {TALK_MIN} min -> {OUT.relative_to(ROOT) or '.'}: "
          f"index.html, {PDF.name}, {SCRIPT.name}, {made} code panels")
