-- Generated by deck.py from the measured HTML layout. Do not edit.
-- Run: osascript scripts/build-key.applescript --force
--
-- This overwrites Rolle speaker base.key wholesale, losing anything done by hand in
-- Keynote, so it will not run without --force.

on run argv
if argv does not contain "--force" then
  error "Refusing to rebuild: build/Rolle speaker base.key may hold Keynote edits that only exist there. Re-run with --force to overwrite it." number 1
end if

set repoRoot to (do shell script "cd " & quoted form of ((POSIX path of (path to home folder)) & "Projects/keynote-base") & " && pwd")
set assetDir to repoRoot & "/build/keyassets/"
set genDir to repoRoot & "/build/keyassets/"
set outPath to repoRoot & "/build/Rolle speaker base.key"

tell application "Keynote"
  activate
  set doc to make new document with properties {width:1920, height:1080}
  tell doc
    set blankMaster to master slide "Blank"
    set base slide of slide 1 to blankMaster
    set s2 to make new slide with properties {base slide:blankMaster}
    set s3 to make new slide with properties {base slide:blankMaster}
    set s4 to make new slide with properties {base slide:blankMaster}
    set s5 to make new slide with properties {base slide:blankMaster}
    set s6 to make new slide with properties {base slide:blankMaster}
    set s7 to make new slide with properties {base slide:blankMaster}
    set s8 to make new slide with properties {base slide:blankMaster}

    tell slide 1
      make new image with properties {file:(POSIX file (assetDir & "bg.png")), position:{0, 0}, width:1920, height:1080}
      make new image with properties {file:(POSIX file (repoRoot & "/assets/portrait-crop.jpg")), position:{1461, 0}, width:459, height:1080}
      make new image with properties {file:(POSIX file (assetDir & "wpsuomi.png")), position:{108, 76}, width:240, height:57}
      make new image with properties {file:(POSIX file (assetDir & "icons.png")), position:{108, 977}, width:309, height:28}
      set t0 to make new text item with properties {object text:"Event name 2026, City, 1st of January, 2026", position:{104, 142}, width:528, height:55}
      tell object text of t0
        set its font to "Geist-Medium"
        set its size to 24
        set its color to {21331, 17990, 26985}
      end tell
      set position of t0 to {104, 142}
      set t1 to make new text item with properties {object text:"Talking about", position:{102, 289}, width:1423, height:195}
      tell object text of t1
        set its font to "Unbounded-Regular_ExtraBold"
        set its size to 138
        set its color to {6425, 2056, 13364}
      end tell
      set position of t1 to {102, 289}
      set t2 to make new text item with properties {object text:"something great", position:{111, 402}, width:1423, height:250}
      tell object text of t2
        set its font to "InstrumentSerif-Italic"
        set its size to 174
        set its color to {19532, 7453, 38293}
      end tell
      set position of t2 to {111, 402}
      set t3 to make new text item with properties {object text:"One line that says what this is,", position:{104, 625}, width:1423, height:73}
      tell object text of t3
        set its font to "Geist-Regular"
        set its size to 38
        set its color to {14906, 8738, 16448}
      end tell
      set position of t3 to {104, 625}
      set t4 to make new text item with properties {object text:"and one that says why it matters", position:{104, 677}, width:1423, height:73}
      tell object text of t4
        set its font to "Geist-Regular"
        set its size to 38
        set its color to {14906, 8738, 16448}
      end tell
      set position of t4 to {104, 677}
      set t5 to make new text item with properties {object text:"Rolle Laukkarinen", position:{104, 867}, width:1423, height:71}
      tell object text of t5
        set its font to "Geist-SemiBold"
        set its size to 36
        set its color to {6425, 2056, 13364}
      end tell
      set position of t5 to {104, 867}
      set t6 to make new text item with properties {object text:"Founder and CTO, Digitoimisto Dude Oy", position:{104, 917}, width:1423, height:62}
      tell object text of t6
        set its font to "Geist-Regular"
        set its size to 29
        set its color to {19018, 15420, 20046}
      end tell
      set position of t6 to {104, 917}
      set t7 to make new text item with properties {object text:"→ rolle.social", position:{435, 969}, width:186, height:58}
      tell object text of t7
        set its font to "Geist-Medium"
        set its size to 26
        set its color to {19018, 15420, 20046}
      end tell
      set position of t7 to {435, 969}
    end tell

    tell s2
      make new image with properties {file:(POSIX file (assetDir & "bg.png")), position:{0, 0}, width:1920, height:1080}
      make new image with properties {file:(POSIX file (genDir & "prog-2.png")), position:{1376, 976}, width:460, height:32}
      set t0 to make new text item with properties {object text:"About me", position:{103, 311}, width:1813, height:130}
      tell object text of t0
        set its font to "Unbounded-Regular_ExtraBold"
        set its size to 64
        set its color to {6425, 2056, 13364}
      end tell
      tell characters 7 thru 8 of object text of t0
        set its font to "InstrumentSerif-Italic"
        set its size to 82
        set its color to {19532, 7453, 38293}
      end tell
      set position of t0 to {103, 311}
      set t1 to make new text item with properties {object text:"Two short sections for the speaker slide. Photos stack full-bleed on the right when the talk supplies them.", position:{104, 423}, width:1813, height:68}
      tell object text of t1
        set its font to "Geist-Regular"
        set its size to 34
        set its color to {11822, 6939, 13364}
      end tell
      set position of t1 to {104, 423}
      set t2 to make new text item with properties {object text:"And the company", position:{103, 520}, width:1813, height:130}
      tell object text of t2
        set its font to "Unbounded-Regular_ExtraBold"
        set its size to 64
        set its color to {6425, 2056, 13364}
      end tell
      tell characters 5 thru 15 of object text of t2
        set its font to "InstrumentSerif-Italic"
        set its size to 82
        set its color to {19532, 7453, 38293}
      end tell
      set position of t2 to {103, 520}
      set t3 to make new text item with properties {object text:"Keep each one to three lines. The heading does the work, the paragraph gives the room something to read while you talk.", position:{104, 631}, width:1813, height:68}
      tell object text of t3
        set its font to "Geist-Regular"
        set its size to 34
        set its color to {11822, 6939, 13364}
      end tell
      set position of t3 to {104, 631}
      set t4 to make new text item with properties {object text:"Talking about something great", position:{104, 972}, width:361, height:55}
      tell object text of t4
        set its font to "Geist-Regular"
        set its size to 24
        set its color to {19018, 15420, 20046}
      end tell
      set position of t4 to {104, 972}
    end tell

    tell s3
      make new image with properties {file:(POSIX file (assetDir & "bg.png")), position:{0, 0}, width:1920, height:1080}
      make new image with properties {file:(POSIX file (genDir & "prog-3.png")), position:{1352, 976}, width:460, height:32}
      set t0 to make new text item with properties {object text:"One idea,", position:{102, 345}, width:1788, height:139}
      tell object text of t0
        set its font to "Unbounded-Regular_ExtraBold"
        set its size to 92
        set its color to {6425, 2056, 13364}
      end tell
      set position of t0 to {102, 345}
      set t1 to make new text item with properties {object text:"said plainly", position:{103, 421}, width:1788, height:178}
      tell object text of t1
        set its font to "InstrumentSerif-Italic"
        set its size to 118
        set its color to {19532, 7453, 38293}
      end tell
      set position of t1 to {103, 421}
      set t2 to make new text item with properties {object text:"For section breaks, and for the lines", position:{104, 591}, width:1788, height:71}
      tell object text of t2
        set its font to "Geist-Regular"
        set its size to 36
        set its color to {14906, 8738, 16448}
      end tell
      set position of t2 to {104, 591}
      set t3 to make new text item with properties {object text:"you want the room to remember.", position:{104, 640}, width:1788, height:71}
      tell object text of t3
        set its font to "Geist-Regular"
        set its size to 36
        set its color to {14906, 8738, 16448}
      end tell
      set position of t3 to {104, 640}
      set t4 to make new text item with properties {object text:"Talking about something great", position:{104, 972}, width:361, height:55}
      tell object text of t4
        set its font to "Geist-Regular"
        set its size to 24
        set its color to {19018, 15420, 20046}
      end tell
      set position of t4 to {104, 972}
    end tell

    tell s4
      make new image with properties {file:(POSIX file (assetDir & "bg.png")), position:{0, 0}, width:1920, height:1080}
      make new image with properties {file:(POSIX file (genDir & "prog-4.png")), position:{1352, 976}, width:460, height:32}
      set t0 to make new text item with properties {object text:"Four things, side by side", position:{103, 212}, width:1788, height:151}
      tell object text of t0
        set its font to "Unbounded-Regular_ExtraBold"
        set its size to 76
        set its color to {6425, 2056, 13364}
      end tell
      tell characters 14 thru 25 of object text of t0
        set its font to "InstrumentSerif-Italic"
        set its size to 98
        set its color to {19532, 7453, 38293}
      end tell
      set position of t0 to {103, 212}
      set t1 to make new text item with properties {object text:"Label", position:{102, 379}, width:846, height:76}
      tell object text of t1
        set its font to "Unbounded-Regular_SemiBold"
        set its size to 42
        set its color to {19532, 7453, 38293}
      end tell
      set position of t1 to {102, 379}
      set t2 to make new text item with properties {object text:"Two lines of body copy at most, or it stops being a label.", position:{104, 444}, width:846, height:68}
      tell object text of t2
        set its font to "Geist-Regular"
        set its size to 34
        set its color to {11822, 6939, 13364}
      end tell
      set position of t2 to {104, 444}
      set t3 to make new text item with properties {object text:"Contrast", position:{1008, 379}, width:846, height:76}
      tell object text of t3
        set its font to "Unbounded-Regular_SemiBold"
        set its size to 42
        set its color to {19532, 7453, 38293}
      end tell
      set position of t3 to {1008, 379}
      set t4 to make new text item with properties {object text:"Everything on the slide clears 7.5:1 against the ground.", position:{1010, 444}, width:846, height:68}
      tell object text of t4
        set its font to "Geist-Regular"
        set its size to 34
        set its color to {11822, 6939, 13364}
      end tell
      set position of t4 to {1010, 444}
      set t5 to make new text item with properties {object text:"Type", position:{102, 609}, width:846, height:76}
      tell object text of t5
        set its font to "Unbounded-Regular_SemiBold"
        set its size to 42
        set its color to {19532, 7453, 38293}
      end tell
      set position of t5 to {102, 609}
      set t6 to make new text item with properties {object text:"Unbounded for the noun, Instrument Serif for the counter-phrase.", position:{104, 674}, width:846, height:68}
      tell object text of t6
        set its font to "Geist-Regular"
        set its size to 34
        set its color to {11822, 6939, 13364}
      end tell
      set position of t6 to {104, 674}
      set t7 to make new text item with properties {object text:"Space", position:{1008, 609}, width:846, height:76}
      tell object text of t7
        set its font to "Unbounded-Regular_SemiBold"
        set its size to 42
        set its color to {19532, 7453, 38293}
      end tell
      set position of t7 to {1008, 609}
      set t8 to make new text item with properties {object text:"Hierarchy is size and space. No borders, no cards.", position:{1010, 674}, width:846, height:68}
      tell object text of t8
        set its font to "Geist-Regular"
        set its size to 34
        set its color to {11822, 6939, 13364}
      end tell
      set position of t8 to {1010, 674}
      set t9 to make new text item with properties {object text:"Talking about something great", position:{104, 972}, width:361, height:55}
      tell object text of t9
        set its font to "Geist-Regular"
        set its size to 24
        set its color to {19018, 15420, 20046}
      end tell
      set position of t9 to {104, 972}
    end tell

    tell s5
      make new image with properties {file:(POSIX file (assetDir & "bg.png")), position:{0, 0}, width:1920, height:1080}
      make new image with properties {file:(POSIX file (genDir & "prog-5.png")), position:{1352, 976}, width:460, height:32}
      set t0 to make new text item with properties {object text:"A short list", position:{103, 250}, width:1788, height:151}
      tell object text of t0
        set its font to "Unbounded-Regular_ExtraBold"
        set its size to 76
        set its color to {6425, 2056, 13364}
      end tell
      tell characters 9 thru 12 of object text of t0
        set its font to "InstrumentSerif-Italic"
        set its size to 98
        set its color to {19532, 7453, 38293}
      end tell
      set position of t0 to {103, 250}
      set t1 to make new text item with properties {object text:"—", position:{104, 417}, width:78, height:73}
      tell object text of t1
        set its font to "Geist-Regular"
        set its size to 38
        set its color to {19532, 7453, 38293}
      end tell
      set position of t1 to {104, 417}
      set t2 to make new text item with properties {object text:"No borders.", position:{164, 417}, width:223, height:73}
      tell object text of t2
        set its font to "Geist-Regular"
        set its size to 38
        set its color to {11822, 6939, 13364}
      end tell
      set position of t2 to {164, 417}
      set t3 to make new text item with properties {object text:"—", position:{104, 504}, width:78, height:73}
      tell object text of t3
        set its font to "Geist-Regular"
        set its size to 38
        set its color to {19532, 7453, 38293}
      end tell
      set position of t3 to {104, 504}
      set t4 to make new text item with properties {object text:"No ALL CAPS, eyebrows and labels included.", position:{164, 504}, width:819, height:73}
      tell object text of t4
        set its font to "Geist-Regular"
        set its size to 38
        set its color to {11822, 6939, 13364}
      end tell
      set position of t4 to {164, 504}
      set t5 to make new text item with properties {object text:"—", position:{104, 591}, width:78, height:73}
      tell object text of t5
        set its font to "Geist-Regular"
        set its size to 38
        set its color to {19532, 7453, 38293}
      end tell
      set position of t5 to {104, 591}
      set t6 to make new text item with properties {object text:"No rounded cards with tinted fills.", position:{164, 591}, width:623, height:73}
      tell object text of t6
        set its font to "Geist-Regular"
        set its size to 38
        set its color to {11822, 6939, 13364}
      end tell
      set position of t6 to {164, 591}
      set t7 to make new text item with properties {object text:"—", position:{104, 677}, width:78, height:73}
      tell object text of t7
        set its font to "Geist-Regular"
        set its size to 38
        set its color to {19532, 7453, 38293}
      end tell
      set position of t7 to {104, 677}
      set t8 to make new text item with properties {object text:"Type runs large, and headings stay short.", position:{164, 677}, width:751, height:73}
      tell object text of t8
        set its font to "Geist-Regular"
        set its size to 38
        set its color to {11822, 6939, 13364}
      end tell
      set position of t8 to {164, 677}
      set t9 to make new text item with properties {object text:"Talking about something great", position:{104, 972}, width:361, height:55}
      tell object text of t9
        set its font to "Geist-Regular"
        set its size to 24
        set its color to {19018, 15420, 20046}
      end tell
      set position of t9 to {104, 972}
    end tell

    tell s6
      make new image with properties {file:(POSIX file (assetDir & "bg.png")), position:{0, 0}, width:1920, height:1080}
      make new image with properties {file:(POSIX file (genDir & "prog-6.png")), position:{1352, 976}, width:460, height:32}
      set t0 to make new text item with properties {object text:"What the base gives you", position:{103, 218}, width:1788, height:151}
      tell object text of t0
        set its font to "Unbounded-Regular_ExtraBold"
        set its size to 76
        set its color to {6425, 2056, 13364}
      end tell
      tell characters 15 thru 23 of object text of t0
        set its font to "InstrumentSerif-Italic"
        set its size to 98
        set its color to {19532, 7453, 38293}
      end tell
      set position of t0 to {103, 218}
      set t1 to make new text item with properties {object text:"—", position:{104, 386}, width:64, height:63}
      tell object text of t1
        set its font to "Geist-Regular"
        set its size to 30
        set its color to {19532, 7453, 38293}
      end tell
      set position of t1 to {104, 386}
      set t2 to make new text item with properties {object text:"Cover with portrait", position:{150, 386}, width:281, height:63}
      tell object text of t2
        set its font to "Geist-Regular"
        set its size to 30
        set its color to {11822, 6939, 13364}
      end tell
      set position of t2 to {150, 386}
      set t3 to make new text item with properties {object text:"—", position:{104, 453}, width:64, height:63}
      tell object text of t3
        set its font to "Geist-Regular"
        set its size to 30
        set its color to {19532, 7453, 38293}
      end tell
      set position of t3 to {104, 453}
      set t4 to make new text item with properties {object text:"Statement", position:{150, 453}, width:165, height:63}
      tell object text of t4
        set its font to "Geist-Regular"
        set its size to 30
        set its color to {11822, 6939, 13364}
      end tell
      set position of t4 to {150, 453}
      set t5 to make new text item with properties {object text:"—", position:{104, 520}, width:64, height:63}
      tell object text of t5
        set its font to "Geist-Regular"
        set its size to 30
        set its color to {19532, 7453, 38293}
      end tell
      set position of t5 to {104, 520}
      set t6 to make new text item with properties {object text:"Pairs", position:{150, 520}, width:87, height:63}
      tell object text of t6
        set its font to "Geist-Regular"
        set its size to 30
        set its color to {11822, 6939, 13364}
      end tell
      set position of t6 to {150, 520}
      set t7 to make new text item with properties {object text:"—", position:{104, 587}, width:64, height:63}
      tell object text of t7
        set its font to "Geist-Regular"
        set its size to 30
        set its color to {19532, 7453, 38293}
      end tell
      set position of t7 to {104, 587}
      set t8 to make new text item with properties {object text:"Bullets", position:{150, 587}, width:115, height:63}
      tell object text of t8
        set its font to "Geist-Regular"
        set its size to 30
        set its color to {11822, 6939, 13364}
      end tell
      set position of t8 to {150, 587}
      set t9 to make new text item with properties {object text:"—", position:{104, 654}, width:64, height:63}
      tell object text of t9
        set its font to "Geist-Regular"
        set its size to 30
        set its color to {19532, 7453, 38293}
      end tell
      set position of t9 to {104, 654}
      set t10 to make new text item with properties {object text:"A dense list like this one", position:{150, 654}, width:361, height:63}
      tell object text of t10
        set its font to "Geist-Regular"
        set its size to 30
        set its color to {11822, 6939, 13364}
      end tell
      set position of t10 to {150, 654}
      set t11 to make new text item with properties {object text:"—", position:{104, 721}, width:64, height:63}
      tell object text of t11
        set its font to "Geist-Regular"
        set its size to 30
        set its color to {19532, 7453, 38293}
      end tell
      set position of t11 to {104, 721}
      set t12 to make new text item with properties {object text:"Code panels", position:{150, 721}, width:194, height:63}
      tell object text of t12
        set its font to "Geist-Regular"
        set its size to 30
        set its color to {11822, 6939, 13364}
      end tell
      set position of t12 to {150, 721}
      set t13 to make new text item with properties {object text:"—", position:{937, 386}, width:64, height:63}
      tell object text of t13
        set its font to "Geist-Regular"
        set its size to 30
        set its color to {19532, 7453, 38293}
      end tell
      set position of t13 to {937, 386}
      set t14 to make new text item with properties {object text:"Real syntax highlighting", position:{983, 386}, width:357, height:63}
      tell object text of t14
        set its font to "Geist-Regular"
        set its size to 30
        set its color to {11822, 6939, 13364}
      end tell
      set position of t14 to {983, 386}
      set t15 to make new text item with properties {object text:"—", position:{937, 453}, width:64, height:63}
      tell object text of t15
        set its font to "Geist-Regular"
        set its size to 30
        set its color to {19532, 7453, 38293}
      end tell
      set position of t15 to {937, 453}
      set t16 to make new text item with properties {object text:"A timing bar, not page numbers", position:{983, 453}, width:462, height:63}
      tell object text of t16
        set its font to "Geist-Regular"
        set its size to 30
        set its color to {11822, 6939, 13364}
      end tell
      set position of t16 to {983, 453}
      set t17 to make new text item with properties {object text:"—", position:{937, 520}, width:64, height:63}
      tell object text of t17
        set its font to "Geist-Regular"
        set its size to 30
        set its color to {19532, 7453, 38293}
      end tell
      set position of t17 to {937, 520}
      set t18 to make new text item with properties {object text:"HTML output", position:{983, 520}, width:201, height:63}
      tell object text of t18
        set its font to "Geist-Regular"
        set its size to 30
        set its color to {11822, 6939, 13364}
      end tell
      set position of t18 to {983, 520}
      set t19 to make new text item with properties {object text:"—", position:{937, 587}, width:64, height:63}
      tell object text of t19
        set its font to "Geist-Regular"
        set its size to 30
        set its color to {19532, 7453, 38293}
      end tell
      set position of t19 to {937, 587}
      set t20 to make new text item with properties {object text:"PDF output", position:{983, 587}, width:178, height:63}
      tell object text of t20
        set its font to "Geist-Regular"
        set its size to 30
        set its color to {11822, 6939, 13364}
      end tell
      set position of t20 to {983, 587}
      set t21 to make new text item with properties {object text:"—", position:{937, 654}, width:64, height:63}
      tell object text of t21
        set its font to "Geist-Regular"
        set its size to 30
        set its color to {19532, 7453, 38293}
      end tell
      set position of t21 to {937, 654}
      set t22 to make new text item with properties {object text:"A Keynote master", position:{983, 654}, width:268, height:63}
      tell object text of t22
        set its font to "Geist-Regular"
        set its size to 30
        set its color to {11822, 6939, 13364}
      end tell
      set position of t22 to {983, 654}
      set t23 to make new text item with properties {object text:"—", position:{937, 721}, width:64, height:63}
      tell object text of t23
        set its font to "Geist-Regular"
        set its size to 30
        set its color to {19532, 7453, 38293}
      end tell
      set position of t23 to {937, 721}
      set t24 to make new text item with properties {object text:"One source for all three", position:{983, 721}, width:350, height:63}
      tell object text of t24
        set its font to "Geist-Regular"
        set its size to 30
        set its color to {11822, 6939, 13364}
      end tell
      set position of t24 to {983, 721}
      set t25 to make new text item with properties {object text:"Talking about something great", position:{104, 972}, width:361, height:55}
      tell object text of t25
        set its font to "Geist-Regular"
        set its size to 24
        set its color to {19018, 15420, 20046}
      end tell
      set position of t25 to {104, 972}
    end tell

    tell s7
      make new image with properties {file:(POSIX file (assetDir & "bg.png")), position:{0, 0}, width:1920, height:1080}
      make new image with properties {file:(POSIX file (genDir & "code-7-left.png")), position:{108, 413}, width:819, height:92}
      make new image with properties {file:(POSIX file (genDir & "code-7-right.png")), position:{993, 413}, width:819, height:252}
      make new image with properties {file:(POSIX file (genDir & "prog-7.png")), position:{1352, 976}, width:460, height:32}
      set t0 to make new text item with properties {object text:"One field, two ways", position:{103, 181}, width:1788, height:151}
      tell object text of t0
        set its font to "Unbounded-Regular_ExtraBold"
        set its size to 76
        set its color to {6425, 2056, 13364}
      end tell
      tell characters 12 thru 19 of object text of t0
        set its font to "InstrumentSerif-Italic"
        set its size to 98
        set its color to {19532, 7453, 38293}
      end tell
      set position of t0 to {103, 181}
      set t1 to make new text item with properties {object text:"With the plugin", position:{103, 341}, width:868, height:79}
      tell object text of t1
        set its font to "InstrumentSerif-Regular"
        set its size to 42
        set its color to {19532, 7453, 38293}
      end tell
      set position of t1 to {103, 341}
      set t2 to make new text item with properties {object text:"With core", position:{988, 341}, width:868, height:79}
      tell object text of t2
        set its font to "InstrumentSerif-Regular"
        set its size to 42
        set its color to {19532, 7453, 38293}
      end tell
      set position of t2 to {988, 341}
      set t3 to make new text item with properties {object text:"Four more lines, and the value now has a type, a schema and a REST route. The theme stops being the only thing that knows the field exists.", position:{104, 709}, width:1638, height:65}
      tell object text of t3
        set its font to "Geist-Regular"
        set its size to 32
        set its color to {11822, 6939, 13364}
      end tell
      set position of t3 to {104, 709}
      set t4 to make new text item with properties {object text:"Talking about something great", position:{104, 972}, width:361, height:55}
      tell object text of t4
        set its font to "Geist-Regular"
        set its size to 24
        set its color to {19018, 15420, 20046}
      end tell
      set position of t4 to {104, 972}
    end tell

    tell s8
      make new image with properties {file:(POSIX file (assetDir & "bg.png")), position:{0, 0}, width:1920, height:1080}
      make new image with properties {file:(POSIX file (genDir & "prog-8.png")), position:{1352, 976}, width:460, height:32}
      set t0 to make new text item with properties {object text:"Kiitos.", position:{102, 345}, width:1788, height:139}
      tell object text of t0
        set its font to "Unbounded-Regular_ExtraBold"
        set its size to 92
        set its color to {6425, 2056, 13364}
      end tell
      set position of t0 to {102, 345}
      set t1 to make new text item with properties {object text:"Questions?", position:{103, 421}, width:1788, height:178}
      tell object text of t1
        set its font to "InstrumentSerif-Italic"
        set its size to 118
        set its color to {19532, 7453, 38293}
      end tell
      set position of t1 to {103, 421}
      set t2 to make new text item with properties {object text:"Rolle Laukkarinen", position:{104, 591}, width:1788, height:71}
      tell object text of t2
        set its font to "Geist-Regular"
        set its size to 36
        set its color to {14906, 8738, 16448}
      end tell
      set position of t2 to {104, 591}
      set t3 to make new text item with properties {object text:"rolle.social", position:{104, 640}, width:1788, height:71}
      tell object text of t3
        set its font to "Geist-Regular"
        set its size to 36
        set its color to {14906, 8738, 16448}
      end tell
      set position of t3 to {104, 640}
      set t4 to make new text item with properties {object text:"Talking about something great", position:{104, 972}, width:361, height:55}
      tell object text of t4
        set its font to "Geist-Regular"
        set its size to 24
        set its color to {19018, 15420, 20046}
      end tell
      set position of t4 to {104, 972}
    end tell

    save doc in POSIX file outPath
  end tell
end tell
end run
