-- Generated by deck.py. Do not edit; edit the deck source and regenerate.
-- Run: osascript scripts/build-key.applescript --force
-- Static bitmaps come from scripts/build-assets.sh, the rest from deck.py.
--
-- This overwrites Rolle speaker base.key wholesale, losing anything done by hand in
-- Keynote, so it will not run without --force.

on run argv
if argv does not contain "--force" then
  error "Refusing to rebuild: build/Rolle speaker base.key may hold Keynote edits that only exist there. Re-run with --force to overwrite it." number 1
end if

set repoRoot to (do shell script "cd " & quoted form of ((POSIX path of (path to home folder)) & "Projects/keynote-base") & " && pwd")
set assetDir to repoRoot & "/build/keyassets/"
set genDir to repoRoot & "/build/keyassets/"
set outPath to repoRoot & "/build/Rolle speaker base.key"

-- Palette, 16-bit channels
set inkColor to {6425, 2056, 13364} -- #190834
set violetColor to {19532, 7453, 38293} -- #4C1D95
set subtitleColor to {14906, 8738, 16448} -- #3A2240
set secondaryColor to {19018, 15420, 20046} -- #4A3C4E
set bodyColor to {11822, 6939, 13364} -- #2E1B34
set panelInkColor to {11051, 6939, 13107} -- #2B1B33
set eventColor to {21331, 18018, 26985} -- #534669
set progressColor to {11822, 3855, 24158} -- #2E0F5E
set progressMutedColor to {20303, 16962, 29298} -- #4F4272

tell application "Keynote"
  activate
  set doc to make new document with properties {width:1920, height:1080}
  tell doc
    set blankMaster to master slide "Blank"
    set base slide of slide 1 to blankMaster
    set s2 to make new slide with properties {base slide:blankMaster}
    set s3 to make new slide with properties {base slide:blankMaster}
    set s4 to make new slide with properties {base slide:blankMaster}
    set s5 to make new slide with properties {base slide:blankMaster}
    set s6 to make new slide with properties {base slide:blankMaster}
    set s7 to make new slide with properties {base slide:blankMaster}

    tell slide 1
      make new image with properties {file:(POSIX file (assetDir & "bg.png")), position:{0, 0}, width:1920, height:1080}
      make new image with properties {file:(POSIX file (repoRoot & "/assets/portrait-crop.jpg")), position:{1461, 0}, width:459, height:1080}
      make new image with properties {file:(POSIX file (assetDir & "wpsuomi.png")), position:{108, 76}, width:240, height:57}
      make new image with properties {file:(POSIX file (assetDir & "icons.png")), position:{108, 979}, width:309, height:28}
      set ev to make new text item with properties {object text:"Event name 2026, City, 1st of January, 2026", position:{106, 152}, width:1000, height:34}
      tell object text of ev
        set its font to "Geist-Medium"
        set its size to 24
        set its color to eventColor
      end tell
      set h1a to make new text item with properties {object text:"Talking about", position:{108, 302}, width:1100, height:150}
      tell object text of h1a
        set its font to "Unbounded-Regular_ExtraBold"
        set its size to 138
        set its color to inkColor
      end tell
      set h1b to make new text item with properties {object text:"something great", position:{108, 416}, width:1100, height:180}
      tell object text of h1b
        set its font to "InstrumentSerif-Italic"
        set its size to 174
        set its color to violetColor
      end tell
      set sf0 to make new text item with properties {object text:"One line that says what this is,", position:{108, 613}, width:1100, height:52}
      tell object text of sf0
        set its font to "Geist-Regular"
        set its size to 38
        set its color to subtitleColor
      end tell
      set sf1 to make new text item with properties {object text:"and one that says why it matters", position:{108, 665}, width:1100, height:52}
      tell object text of sf1
        set its font to "Geist-Regular"
        set its size to 38
        set its color to subtitleColor
      end tell
      set by1 to make new text item with properties {object text:"Rolle Laukkarinen", position:{104, 869}, width:1100, height:48}
      tell object text of by1
        set its font to "Geist-SemiBold"
        set its size to 36
        set its color to inkColor
      end tell
      set by2 to make new text item with properties {object text:"Founder and CTO, Digitoimisto Dude Oy", position:{104, 917}, width:1100, height:40}
      tell object text of by2
        set its font to "Geist-Regular"
        set its size to 29
        set its color to secondaryColor
      end tell
      set by3 to make new text item with properties {object text:"→  rolle.social", position:{433, 975}, width:500, height:36}
      tell object text of by3
        set its font to "Geist-Medium"
        set its size to 26
        set its color to secondaryColor
      end tell
    end tell

    tell s2
      make new image with properties {file:(POSIX file (assetDir & "bg.png")), position:{0, 0}, width:1920, height:1080}
      set sa to make new text item with properties {object text:"One idea,", position:{108, 300}, width:1704, height:150}
      tell object text of sa
        set its font to "Unbounded-Regular_ExtraBold"
        set its size to 108
        set its color to inkColor
      end tell
      set sb to make new text item with properties {object text:"said plainly", position:{108, 420}, width:1704, height:190}
      tell object text of sb
        set its font to "InstrumentSerif-Italic"
        set its size to 140
        set its color to violetColor
      end tell
      set ss0 to make new text item with properties {object text:"For section breaks, and for the lines", position:{108, 660}, width:1500, height:56}
      tell object text of ss0
        set its font to "Geist-Regular"
        set its size to 40
        set its color to subtitleColor
      end tell
      set ss1 to make new text item with properties {object text:"you want the room to remember.", position:{108, 716}, width:1500, height:56}
      tell object text of ss1
        set its font to "Geist-Regular"
        set its size to 40
        set its color to subtitleColor
      end tell
      set fr to make new text item with properties {object text:"Talking about something great", position:{108, 946}, width:900, height:40}
      tell object text of fr
        set its font to "Geist-Regular"
        set its size to 26
        set its color to secondaryColor
      end tell
      make new image with properties {file:(POSIX file (genDir & "prog-2.png")), position:{1352, 950}, width:460, height:32}
    end tell

    tell s3
      make new image with properties {file:(POSIX file (assetDir & "bg.png")), position:{0, 0}, width:1920, height:1080}
      set hd to make new text item with properties {object text:"Four things, side by side", position:{108, 96}, width:1704, height:191}
      tell object text of hd
        set its font to "Unbounded-Regular_ExtraBold"
        set its size to 102
        set its color to inkColor
      end tell
      tell characters 14 thru 25 of object text of hd
        set its font to "InstrumentSerif-Italic"
        set its size to 132
        set its color to violetColor
      end tell
      set pl0 to make new text item with properties {object text:"Label", position:{108, 300}, width:798, height:70}
      tell object text of pl0
        set its font to "Unbounded-Regular_SemiBold"
        set its size to 51
        set its color to violetColor
      end tell
      set pb0 to make new text item with properties {object text:"Two lines of body copy at most, or it stops being a label.", position:{108, 376}, width:798, height:150}
      tell object text of pb0
        set its font to "Geist-Regular"
        set its size to 37
        set its color to bodyColor
      end tell
      set pl1 to make new text item with properties {object text:"Contrast", position:{1014, 300}, width:798, height:70}
      tell object text of pl1
        set its font to "Unbounded-Regular_SemiBold"
        set its size to 51
        set its color to violetColor
      end tell
      set pb1 to make new text item with properties {object text:"Everything on the slide clears 7.5:1 against the ground.", position:{1014, 376}, width:798, height:150}
      tell object text of pb1
        set its font to "Geist-Regular"
        set its size to 37
        set its color to bodyColor
      end tell
      set pl2 to make new text item with properties {object text:"Type", position:{108, 560}, width:798, height:70}
      tell object text of pl2
        set its font to "Unbounded-Regular_SemiBold"
        set its size to 51
        set its color to violetColor
      end tell
      set pb2 to make new text item with properties {object text:"Unbounded for the noun, Instrument Serif for the counter-phrase.", position:{108, 636}, width:798, height:150}
      tell object text of pb2
        set its font to "Geist-Regular"
        set its size to 37
        set its color to bodyColor
      end tell
      set pl3 to make new text item with properties {object text:"Space", position:{1014, 560}, width:798, height:70}
      tell object text of pl3
        set its font to "Unbounded-Regular_SemiBold"
        set its size to 51
        set its color to violetColor
      end tell
      set pb3 to make new text item with properties {object text:"Hierarchy is size and space. No borders, no cards.", position:{1014, 636}, width:798, height:150}
      tell object text of pb3
        set its font to "Geist-Regular"
        set its size to 37
        set its color to bodyColor
      end tell
      set fr to make new text item with properties {object text:"Talking about something great", position:{108, 946}, width:900, height:40}
      tell object text of fr
        set its font to "Geist-Regular"
        set its size to 26
        set its color to secondaryColor
      end tell
      make new image with properties {file:(POSIX file (genDir & "prog-3.png")), position:{1352, 950}, width:460, height:32}
    end tell

    tell s4
      make new image with properties {file:(POSIX file (assetDir & "bg.png")), position:{0, 0}, width:1920, height:1080}
      set hd to make new text item with properties {object text:"A short list", position:{108, 96}, width:1704, height:191}
      tell object text of hd
        set its font to "Unbounded-Regular_ExtraBold"
        set its size to 102
        set its color to inkColor
      end tell
      tell characters 9 thru 12 of object text of hd
        set its font to "InstrumentSerif-Italic"
        set its size to 132
        set its color to violetColor
      end tell
      set bl0 to make new text item with properties {object text:"—   No borders.", position:{108, 320}, width:1704, height:110}
      tell object text of bl0
        set its font to "Geist-Regular"
        set its size to 44
        set its color to bodyColor
      end tell
      set bl1 to make new text item with properties {object text:"—   No ALL CAPS, eyebrows and labels included.", position:{108, 448}, width:1704, height:110}
      tell object text of bl1
        set its font to "Geist-Regular"
        set its size to 44
        set its color to bodyColor
      end tell
      set bl2 to make new text item with properties {object text:"—   No rounded cards with tinted fills.", position:{108, 576}, width:1704, height:110}
      tell object text of bl2
        set its font to "Geist-Regular"
        set its size to 44
        set its color to bodyColor
      end tell
      set bl3 to make new text item with properties {object text:"—   Type runs large, and headings stay short.", position:{108, 704}, width:1704, height:110}
      tell object text of bl3
        set its font to "Geist-Regular"
        set its size to 44
        set its color to bodyColor
      end tell
      set fr to make new text item with properties {object text:"Talking about something great", position:{108, 946}, width:900, height:40}
      tell object text of fr
        set its font to "Geist-Regular"
        set its size to 26
        set its color to secondaryColor
      end tell
      make new image with properties {file:(POSIX file (genDir & "prog-4.png")), position:{1352, 950}, width:460, height:32}
    end tell

    tell s5
      make new image with properties {file:(POSIX file (assetDir & "bg.png")), position:{0, 0}, width:1920, height:1080}
      set hd to make new text item with properties {object text:"What the base gives you", position:{108, 96}, width:1704, height:191}
      tell object text of hd
        set its font to "Unbounded-Regular_ExtraBold"
        set its size to 102
        set its color to inkColor
      end tell
      tell characters 15 thru 23 of object text of hd
        set its font to "InstrumentSerif-Italic"
        set its size to 132
        set its color to violetColor
      end tell
      set lw0 to make new text item with properties {object text:"—   Cover with portrait", position:{108, 320}, width:528, height:90}
      tell object text of lw0
        set its font to "Geist-Regular"
        set its size to 32
        set its color to bodyColor
      end tell
      set lw1 to make new text item with properties {object text:"—   Statement", position:{108, 418}, width:528, height:90}
      tell object text of lw1
        set its font to "Geist-Regular"
        set its size to 32
        set its color to bodyColor
      end tell
      set lw2 to make new text item with properties {object text:"—   Pairs", position:{108, 516}, width:528, height:90}
      tell object text of lw2
        set its font to "Geist-Regular"
        set its size to 32
        set its color to bodyColor
      end tell
      set lw3 to make new text item with properties {object text:"—   Bullets", position:{108, 614}, width:528, height:90}
      tell object text of lw3
        set its font to "Geist-Regular"
        set its size to 32
        set its color to bodyColor
      end tell
      set lw4 to make new text item with properties {object text:"—   A dense list like this one", position:{108, 712}, width:528, height:90}
      tell object text of lw4
        set its font to "Geist-Regular"
        set its size to 32
        set its color to bodyColor
      end tell
      set lw5 to make new text item with properties {object text:"—   Code panels", position:{108, 810}, width:528, height:90}
      tell object text of lw5
        set its font to "Geist-Regular"
        set its size to 32
        set its color to bodyColor
      end tell
      set lw6 to make new text item with properties {object text:"—   Real syntax highlighting", position:{676, 320}, width:528, height:90}
      tell object text of lw6
        set its font to "Geist-Regular"
        set its size to 32
        set its color to bodyColor
      end tell
      set lw7 to make new text item with properties {object text:"—   A timing bar, not page numbers", position:{676, 418}, width:528, height:90}
      tell object text of lw7
        set its font to "Geist-Regular"
        set its size to 32
        set its color to bodyColor
      end tell
      set lw8 to make new text item with properties {object text:"—   HTML output", position:{676, 516}, width:528, height:90}
      tell object text of lw8
        set its font to "Geist-Regular"
        set its size to 32
        set its color to bodyColor
      end tell
      set lw9 to make new text item with properties {object text:"—   PDF output", position:{676, 614}, width:528, height:90}
      tell object text of lw9
        set its font to "Geist-Regular"
        set its size to 32
        set its color to bodyColor
      end tell
      set lw10 to make new text item with properties {object text:"—   A Keynote master", position:{676, 712}, width:528, height:90}
      tell object text of lw10
        set its font to "Geist-Regular"
        set its size to 32
        set its color to bodyColor
      end tell
      set lw11 to make new text item with properties {object text:"—   One source for all three", position:{676, 810}, width:528, height:90}
      tell object text of lw11
        set its font to "Geist-Regular"
        set its size to 32
        set its color to bodyColor
      end tell
      set fr to make new text item with properties {object text:"Talking about something great", position:{108, 946}, width:900, height:40}
      tell object text of fr
        set its font to "Geist-Regular"
        set its size to 26
        set its color to secondaryColor
      end tell
      make new image with properties {file:(POSIX file (genDir & "prog-5.png")), position:{1352, 950}, width:460, height:32}
    end tell

    tell s6
      make new image with properties {file:(POSIX file (assetDir & "bg.png")), position:{0, 0}, width:1920, height:1080}
      set hd to make new text item with properties {object text:"One field, two ways", position:{108, 90}, width:1704, height:171}
      tell object text of hd
        set its font to "Unbounded-Regular_ExtraBold"
        set its size to 92
        set its color to inkColor
      end tell
      tell characters 12 thru 19 of object text of hd
        set its font to "InstrumentSerif-Italic"
        set its size to 118
        set its color to violetColor
      end tell
      set cl_left to make new text item with properties {object text:"With the plugin", position:{108, 244}, width:819, height:66}
      tell object text of cl_left
        set its font to "InstrumentSerif-Regular"
        set its size to 48
        set its color to violetColor
      end tell
      make new image with properties {file:(POSIX file (genDir & "code-6-left.png")), position:{108, 330}, width:819, height:92}
      set cl_right to make new text item with properties {object text:"With core", position:{993, 244}, width:819, height:66}
      tell object text of cl_right
        set its font to "InstrumentSerif-Regular"
        set its size to 48
        set its color to violetColor
      end tell
      make new image with properties {file:(POSIX file (genDir & "code-6-right.png")), position:{993, 330}, width:819, height:252}
      set tk to make new text item with properties {object text:"Four more lines, and the value now has a type, a schema and a REST route. The theme stops being the only thing that knows the field exists.", position:{108, 630}, width:1704, height:120}
      tell object text of tk
        set its font to "Geist-Regular"
        set its size to 34
        set its color to bodyColor
      end tell
      set fr to make new text item with properties {object text:"Talking about something great", position:{108, 946}, width:900, height:40}
      tell object text of fr
        set its font to "Geist-Regular"
        set its size to 26
        set its color to secondaryColor
      end tell
      make new image with properties {file:(POSIX file (genDir & "prog-6.png")), position:{1352, 950}, width:460, height:32}
    end tell

    tell s7
      make new image with properties {file:(POSIX file (assetDir & "bg.png")), position:{0, 0}, width:1920, height:1080}
      set sa to make new text item with properties {object text:"Kiitos.", position:{108, 300}, width:1704, height:150}
      tell object text of sa
        set its font to "Unbounded-Regular_ExtraBold"
        set its size to 108
        set its color to inkColor
      end tell
      set sb to make new text item with properties {object text:"Questions?", position:{108, 420}, width:1704, height:190}
      tell object text of sb
        set its font to "InstrumentSerif-Italic"
        set its size to 140
        set its color to violetColor
      end tell
      set ss0 to make new text item with properties {object text:"Rolle Laukkarinen", position:{108, 660}, width:1500, height:56}
      tell object text of ss0
        set its font to "Geist-Regular"
        set its size to 40
        set its color to subtitleColor
      end tell
      set ss1 to make new text item with properties {object text:"rolle.social", position:{108, 716}, width:1500, height:56}
      tell object text of ss1
        set its font to "Geist-Regular"
        set its size to 40
        set its color to subtitleColor
      end tell
      set fr to make new text item with properties {object text:"Talking about something great", position:{108, 946}, width:900, height:40}
      tell object text of fr
        set its font to "Geist-Regular"
        set its size to 26
        set its color to secondaryColor
      end tell
      make new image with properties {file:(POSIX file (genDir & "prog-7.png")), position:{1352, 950}, width:460, height:32}
    end tell

    save doc in POSIX file outPath
  end tell
end tell
end run
